const dotenv = require('dotenv');
const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');
dotenv.config({ path: __dirname + '/.env' })

const readline = require('readline');
const rl = readline.createInterface({
	input: process.stdin,
	output: process.stdout
});

// Choose to enable or not Tokenizer (count the cost of the API call in tokens)
// enable it will execute a python script to count the tokens, make sure to have python installed
const enableTokenizer = false;

const OpenAI = require('openai');
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

// Script
async function sendRequest(projectPath, message) {
	const footer = "<br><br> This README was generated by [DocMyFiles](https://github.com/eliooooooo/DocMyFiles).";
	try {
		if (enableTokenizer) {
			exec(`python3 tokenCounter.py "${data}"`, (error, stdout, stderr) => {
				if (error) {
					console.error(`exec error: ${error}`);
					return;
				}
				console.log(`Number of tokens: ${stdout}`);
			});
		}

		console.log(projectPath);

		const answer = await new Promise((resolve) => {
			rl.question('Do you want to send the request? (yes/no) ', (answer) => {
				resolve(answer);
			});
		});

		if (answer.toLowerCase() === 'yes') {
			const response = await openai.chat.completions.create({
				model: 'gpt-3.5-turbo',
				messages: message
			});
		
			fs.writeFileSync(path.join(__dirname, projectPath, 'README.md'), response.choices[0].message.content + footer);
			console.log('README generated in : ' + path.join(__dirname, projectPath, 'README.md'));
		} else {
			console.log('Request not sent.');
		}
		rl.close();
	} catch (err) {
		console.error(err);
	}
}

// Don't forget to custom the avoid table to avoid some files or directories
const projectPath = './project/sae401/';
const avoid = ['node_modules', 'dist', '.git', 'img', 'css', 'bin', 'uploads', 'tests', 'styles', 'assets'];
const description = 'This is a symfony project, call "Interrail Trip" to accompany and guide users on their interrail journeys';

async function processDirectory(projectPath, avoid, description) {
	try {
		const childs = fs.readdirSync(projectPath);
		const message = [
			{ role: 'system', content: 'You are a useful assistant, specialized in programming. You\'re mainly used to generate custom readme files. Here is a short description of my symfony project : ' + description + '. Here are my project files so that you can generate a custom README for me :' },
		];
	
		for (const child of childs) {		
			const childPath = path.join(projectPath, child);

			if (avoid.some(av => childPath.includes(av))) continue;
			console.log('Processing file: ', childPath);
			
			if (fs.statSync(childPath).isFile()) {
				const filePath = path.join(__dirname, childPath);
				const data = await fs.promises.readFile(filePath, 'utf8');

				message.push({ role: 'user', content: 'Here is my ' + childPath + ' file : ```' + data + '```' });
			} else {
				processDirectory(childPath, avoid, description);
			}
		}

		message.push({ role: 'user', content: 'Could you generate a custom README for my project based on the code and comments in the files I provided? The README should be a fully usable file, not a template. It should include an introduction, installation instructions, configuration setup, usage examples.' });
		
		await sendRequest(projectPath, message);
		
	} catch (err) {
		console.error(err);
	}
}

processDirectory(projectPath, avoid, description);